makewiki/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin Site
    path('admin/', admin.site.urls),

    # Wiki App
    path('', include('wiki.urls')),
]

wiki/urls.py
from django.urls import path
from wiki.views import PageList, PageDetailView

app_name = 'wiki'
urlpatterns = [
    path('', PageList.as_view(), name='wiki-list-page'),
    path('<slug:slug>/', PageDetailView.as_view(), name='wiki-details-page'),
    path('<slug:slug>/POST', PageDetailView.as_view(), name='wiki-details-page'),
]

wiki/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone
from django.contrib.auth.models import User


class Page(models.Model):
    """ Represents a single wiki page. """
    title = models.CharField(max_length=settings.WIKI_PAGE_TITLE_MAX_LENGTH,
                             unique=True,
                             help_text="Title of your page.")
    author = models.ForeignKey(User, on_delete=models.PROTECT,
                               help_text="The user that posted this article.")
    slug = models.CharField(max_length=settings.WIKI_PAGE_TITLE_MAX_LENGTH,
                            blank=True, editable=True,
                            help_text=(
                                "Unique URL path to access this page. " +
                                "Generated by the system."))
    content = models.TextField(
        help_text="Write the content of your page here.")
    created = models.DateTimeField(auto_now_add=True,
                                   help_text=(
                                    "The date and time this page was created."
                                    + " Automatically generated when the " +
                                    "model saves."))
    modified = models.DateTimeField(auto_now=True,
                                    help_text=(
                                        "The date and time this page was " +
                                        " updated. Automatically generated " +
                                        " when the model updates."))

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns a fully-qualified path for a page
           (/droxey/my-new-wiki-page).
        """
        path_components = {'username': self.username, 'slug': self.slug}
        return reverse('wiki-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically
            when a new a page is created.
        """
        if not self.pk:  # To detect new objects, check if self.pk exists.
            self.slug = slugify(self.title, allow_unicode=True)

        # Call save on the superclass.
        return super(Page, self).save(*args, **kwargs)

wiki/forms.py
from django import forms
from wiki.models import Page


class PageForm(forms.ModelForm):
    """ Render and process a form based on the Page model. """
    class Meta:
        model = Page
        fields = ['title', 'author', 'content', 'slug']

wiki/views.py
from django.shortcuts import render
from wiki.models import Page
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .forms import PageForm


class PageList(ListView):
    """
    Display all instances of the Page model in a list. READ functionality
    for the whole Collection.
    """
    model = Page
    template_name = 'wiki/list.html'
    context_object_name = 'pages'


class PageDetailView(DetailView):
    """
    Display details of a single Wiki page featured on the site.

    STRETCH CHALLENGES:
      # here I am
        - If True, save the data,
        - If False, display all the errors in the template, above the form
        fields.
      4. Instead of hard-coding the path to redirect to, use the `reverse`
      function to return the path.
      5. After successfully editing a Page, use Django Messages to "flash" the
      user a success message
           - Message Content: REPLACE_WITH_PAGE_TITLE has been successfully
           updated.
    """
    model = Page
    form_class = PageForm

    def get(self, request, slug):
        """ Returns a specific of wiki page by slug. """
        page = self.get_object(self.model.objects)
        template = loader.get_template('wiki/page.html')
        context = {
            'page': page,
            'form': PageForm
        }
        return HttpResponse(template.render(context, request))

    def post(self, request, slug):
        """Checks if the data in the form is valid.
           If True, save the data, and redirect back to the DetailsView.
           If False, display all the errors in the template,
           above the form fields.
        """
        form = PageForm(request.POST or None, instance=self)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(self.get(new_page.slug))
        else:
            pass

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Dani Roxberry <dani@makeschool.com>">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Wiki</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'wiki:wiki-list-page' %}">Zain's Wiki</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'wiki:wiki-list-page' %}">📓 Pages <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <main role="main" class="container">
        {% block content %}
          <h1>Hello, World!</h1>
        {% endblock %}
    </main>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
  </body>

wiki/templates/wiki/list.html
{% extends "base.html" %}
{% block content %}

<h1>Wiki Articles</h1>

<ul>
    {% for page in pages %}
    <li><a href="{{ page.slug }}">{{ page.title }}</a></li>
    {% empty %}
    <li>No pages yet.</li>
    {% endfor %}
</ul>

{% endblock %}

wiki/templates/wiki/page.html
{% extends "base.html" %}

{% block content %}

<h1>{{ page.title }}</h1>
<h3>Written by: {{ page.author }}</h3>
<h4>Date Created: {{ page.created }}</h4>
<h5>Date Modified: {{ page.modified }}</h5>
<p>Article Text: <br> {{ page.content }}</p>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="POST">
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}